version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: apes_postgres
    environment:
      POSTGRES_DB: apes_production
      POSTGRES_USER: apes_user
      POSTGRES_PASSWORD: apes_secure_password_2024
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apes_user -d apes_production"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: apes_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@apes.local
      PGADMIN_DEFAULT_PASSWORD: admin_password_2024
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles:
      - admin
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: apes_network