[tool.importlinter]
root_packages = ["prompt_improver"]
include_external_packages = true

# Contract to detect any torch imports from database layer
[[tool.importlinter.contracts]]
name = "Database Layer Torch Import Detection"
type = "forbidden"
source_modules = [
    "prompt_improver.database"
]
forbidden_modules = [
    "torch",
    "torch.**"
]
unmatched_ignore_imports_alerting = "error"

# Contract to trace ML optimization imports from database
[[tool.importlinter.contracts]]
name = "Database ML Optimization Import Detection"
type = "forbidden"
source_modules = [
    "prompt_improver.database"
]
forbidden_modules = [
    "prompt_improver.ml.optimization.**"
]
unmatched_ignore_imports_alerting = "error"

# Contract to find any path from database.models to torch
[[tool.importlinter.contracts]]
name = "Database Models Torch Path Detection"
type = "forbidden"
source_modules = [
    "prompt_improver.database.models"
]
forbidden_modules = [
    "torch",
    "torch.**",
    "sklearn.**"
]
unmatched_ignore_imports_alerting = "error"