# Machine Learning Optimizer Configuration
# ------------------------------------
# This file contains settings for the ML components of the rule engine.

# MLflow Configuration
mlflow:
  # The URI for the MLflow tracking server.
  # This can be a local path (e.g., file:///path/to/mlruns) or a remote server URI.
  tracking_uri: "file://../mlruns"
  
  # The name of the experiment under which to log runs.
  experiment_name: "PromptImprover-RuleOptimization"

# Model Configuration
models:
  # Path to the serialized rule effectiveness prediction model.
  # This model predicts the impact of applying a given rule.
  effectiveness_predictor_path: "models/rule_effectiveness_v1.joblib"
  
  # Configuration for the rule parameter optimization (Optuna).
  parameter_optimizer:
    n_trials: 100 # Number of optimization trials to run.
    timeout: 3600 # Timeout in seconds for the optimization study.

# Data Configuration
data:
  # Path to the dataset used for training and evaluating ML models.
  evaluation_dataset_path: "data/evaluation_prompts.csv" 