# Prometheus Configuration - 2025 Best Practices
# Comprehensive monitoring for APES ML Pipeline Orchestrator

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'apes-development'
    environment: 'dev'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # APES Application
  - job_name: 'apes-application'
    static_configs:
      - targets: ['localhost:8000', 'localhost:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 15s
    metrics_path: /metrics

  # Python application metrics (if using prometheus_client)
  - job_name: 'apes-python-metrics'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 5s
    metrics_path: /api/v1/metrics
    scrape_timeout: 10s

  # ML Model metrics
  - job_name: 'apes-ml-metrics'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 10s
    metrics_path: /api/v1/ml/metrics
    scrape_timeout: 15s

  # Health check endpoints
  - job_name: 'apes-health'
    static_configs:
      - targets: ['localhost:8000', 'localhost:8080']
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 5s

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration (for production)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"
